-- Seed psp_types from PSP_OPTIONS_BY_LETTER (src/lib/psp-types.ts)
-- Uses UPSERT to sync label, slug, sort_order, letter

INSERT INTO public.psp_types (label, slug, sort_order, letter) VALUES
  ('Accountant', 'accountant', 1, 'A'),
  ('Agent', 'agent', 2, 'A'),
  ('Appraiser', 'appraiser', 3, 'A'),
  ('Architect', 'architect', 4, 'A'),
  ('Asbesto''s', 'asbestos', 5, 'A'),
  ('Attorney''s', 'attorneys', 6, 'A'),
  ('RE Attorney''s', 're_attorneys', 7, 'A'),
  ('Worker''s Comp', 'workers_comp', 8, 'A'),
  ('Bookkeeper', 'bookkeeper', 9, 'B'),
  ('Broker', 'broker', 10, 'B'),
  ('Builder', 'builder', 11, 'B'),
  ('Cleaner', 'cleaner', 12, 'C'),
  ('Concrete', 'concrete', 13, 'C'),
  ('Contractor', 'contractor', 14, 'C'),
  ('Construction', 'construction', 15, 'C'),
  ('Consultant', 'consultant', 16, 'C'),
  ('Consultant''s', 'consultants', 17, 'C'),
  ('Crowdfunding', 'crowdfunding', 18, 'C'),
  ('Developer', 'developer', 19, 'D'),
  ('Electrician', 'electrician', 20, 'E'),
  ('Escrow', 'escrow', 21, 'E'),
  ('Flooring', 'flooring', 22, 'F'),
  ('Framer', 'framer', 23, 'F'),
  ('Gardening', 'gardening', 24, 'G'),
  ('HVAC', 'hvac', 25, 'H'),
  ('Investor', 'investor', 26, 'I'),
  ('Janitorial', 'janitorial', 27, 'J'),
  ('Landscaper', 'landscaper', 28, 'L'),
  ('Loan', 'loan', 29, 'L'),
  ('Loan Executive', 'loan_executive', 30, 'L'),
  ('Loan Originator', 'loan_originator', 31, 'L'),
  ('Loan Processor', 'loan_processor', 32, 'L'),
  ('Mortgage', 'mortgage', 33, 'M'),
  ('Mover''s', 'movers', 34, 'M'),
  ('Painter', 'painter', 35, 'P'),
  ('Pavement', 'pavement', 36, 'P'),
  ('Pest', 'pest', 37, 'P'),
  ('Professional''s', 'professionals', 38, 'P'),
  ('Plumber', 'plumber', 39, 'P'),
  ('Pool', 'pool', 40, 'P'),
  ('Pressure Washer', 'pressure_washer', 41, 'P'),
  ('Real Estate', 'real_estate', 42, 'R'),
  ('Roofing', 'roofing', 43, 'R'),
  ('Sand-Blasting', 'sand_blasting', 44, 'S'),
  ('Solar', 'solar', 45, 'S'),
  ('Squat-Removal', 'squat_removal', 46, 'S'),
  ('Taxes', 'taxes', 47, 'T'),
  ('Transaction Coordinator', 'transaction_coordinator', 48, 'T'),
  ('Trash Bin Cleaner', 'trash_bin_cleaner', 49, 'T'),
  ('Wholesaler', 'wholesaler', 50, 'W'),
  ('Welder', 'welder', 51, 'W'),
  ('Window Cleaner', 'window_cleaner', 52, 'W')
ON CONFLICT (label) DO UPDATE SET
  slug = EXCLUDED.slug,
  sort_order = EXCLUDED.sort_order,
  letter = EXCLUDED.letter;
